# Generated by Django 5.2.4 on 2025-08-06 02:37

import django.db.models.deletion
import news.models.user
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('generator', models.CharField(blank=True, help_text='채널을 생성한 프로그램', max_length=255, null=True)),
                ('title', models.CharField(help_text='채널 이름', max_length=500)),
                ('link', models.URLField(help_text='채널 웹사이트 URL', max_length=1000)),
                ('language', models.CharField(help_text='콘텐츠 언어 (예: en-us)', max_length=10)),
                ('web_master', models.EmailField(blank=True, help_text='채널 관리자 이메일', max_length=255, null=True)),
                ('copyright', models.TextField(blank=True, help_text='저작권 정보', null=True)),
                ('last_build_date', models.DateTimeField(blank=True, help_text='콘텐츠 마지막 업데이트 시간', null=True)),
                ('image_title', models.CharField(blank=True, help_text='대표 이미지 제목', max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, help_text='대표 이미지 URL', max_length=1000, null=True)),
                ('image_link', models.URLField(blank=True, help_text='대표 이미지 클릭 시 이동 URL', max_length=1000, null=True)),
                ('image_width', models.IntegerField(blank=True, help_text='대표 이미지 너비', null=True)),
                ('image_height', models.IntegerField(blank=True, help_text='대표 이미지 높이', null=True)),
                ('description', models.TextField(blank=True, help_text='채널 설명', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('email', models.EmailField(help_text='로그인 시 사용될 사용자의 이메일 주소입니다.', max_length=50, unique=True, verbose_name='이메일')),
                ('name', models.CharField(blank=True, help_text='사용자의 실명 또는 별명입니다.', max_length=30, null=True, verbose_name='이름')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
            },
            managers=[
                ('objects', news.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('title', models.CharField(help_text='기사 제목', max_length=500)),
                ('link', models.URLField(help_text='기사 원문 링크', max_length=1000)),
                ('guid', models.CharField(help_text='기사 고유 식별자', max_length=1000, unique=True)),
                ('pub_date', models.DateTimeField(help_text='기사 발행일')),
                ('description', models.TextField(blank=True, help_text='기사 요약 내용', null=True)),
                ('source', models.CharField(blank=True, help_text='기사 출처', max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, help_text='기사 출처 URL', max_length=1000, null=True)),
                ('channel', models.ForeignKey(help_text='기사가 속한 뉴스 채널', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='news.newschannel')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
