# Generated by Django 5.2.4 on 2025-08-04 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschannel',
            name='copyright',
            field=models.TextField(blank=True, help_text='저작권 정보', null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='description',
            field=models.TextField(blank=True, help_text='채널 설명', null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='generator',
            field=models.CharField(blank=True, help_text='채널을 생성한 프로그램', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='image_height',
            field=models.IntegerField(blank=True, help_text='대표 이미지 높이', null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='image_link',
            field=models.URLField(blank=True, help_text='대표 이미지 클릭 시 이동 URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='image_title',
            field=models.CharField(blank=True, help_text='대표 이미지 제목', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='image_url',
            field=models.URLField(blank=True, help_text='대표 이미지 URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='image_width',
            field=models.IntegerField(blank=True, help_text='대표 이미지 너비', null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='language',
            field=models.CharField(help_text='콘텐츠 언어 (예: en-us)', max_length=10),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='last_build_date',
            field=models.DateTimeField(blank=True, help_text='콘텐츠 마지막 업데이트 시간', null=True),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='link',
            field=models.URLField(help_text='채널 웹사이트 URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='title',
            field=models.CharField(help_text='채널 이름', max_length=500),
        ),
        migrations.AlterField(
            model_name='newschannel',
            name='web_master',
            field=models.EmailField(blank=True, help_text='채널 관리자 이메일', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='channel',
            field=models.ForeignKey(help_text='기사가 속한 뉴스 채널', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='news.newschannel'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='description',
            field=models.TextField(blank=True, help_text='기사 요약 내용', null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='guid',
            field=models.CharField(help_text='기사 고유 식별자', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.URLField(help_text='기사 원문 링크', max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='pub_date',
            field=models.DateTimeField(help_text='기사 발행일'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source',
            field=models.CharField(blank=True, help_text='기사 출처', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source_url',
            field=models.URLField(blank=True, help_text='기사 출처 URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(help_text='기사 제목', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='로그인 시 사용될 사용자의 이메일 주소입니다.', max_length=50, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='사용자의 실명 또는 별명입니다.', max_length=30, null=True, verbose_name='이름'),
        ),
    ]
