# Generated by Django 5.2.4 on 2025-08-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='사용자의 주소입니다.', max_length=255, null=True, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='사용자의 전화번호입니다.', max_length=20, null=True, verbose_name='전화번호'),
        ),
    ]
