# Generated by Django 5.2.4 on 2025-08-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='삭제일시'),
        ),
    ]
